version: "3.8"
services: 
  backend: 
    build: 
      context: . 
      dockerfile: Dockerfile
    command: "python main.py"
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db
  queue:
    build: 
      context: . 
      dockerfile: Dockerfile
    command: "python consumer.py"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    env_file:
      - database.env
    volumes:
      - .dbdata:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432

volumes:
  .dbdata:
