version: "3.8"
services: 
  backend: 
    build: 
      context: . 
      dockerfile: Dockerfile
    command: "python main.py"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db
  queue:
    build: 
      context: . 
      dockerfile: Dockerfile
    env_file:
    - .env
    environment:
      - RABBIT_URL=${RABBIT_URL}
    command: "python consumer.py"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - .dbdata:/var/lib/postgresql/data
