apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-using-kubectl
spec:
  inputs:
    resources:
      - name: py-microservices
        type: git
    params:
      - name: pathToYamlFile
        description: The path to the yaml file to deploy within the git source
      - name: pathToServiceFile
        description: The yaml service file
      - name: namespace
        description: The namespace To use
  steps:
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "/workspace/django-flask-microservices/$(inputs.params.pathToYamlFile)"
        - "-f"
        - "/workspace/django-flask-microservices/$(inputs.params.pathToServiceFile)"
        - "-n"
        - "$(inputs.params.namespace)"
