apiVersion: v1
kind: Service
metadata:
  name: admin
  labels:
    name: admin
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: admin
