version: "3.8"
services: 
  nginx:
    build: ../nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - backend
  backend: 
    build: 
      context: . 
      dockerfile: Dockerfile
    # command: "python manage.py runserver 0.0.0.0:8000"
    env_file:
    - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - 8000:8000
    volumes:
      - static:/static
    # depends_on:
    #   - db
  # queue:
  #   build: 
  #     context: . 
  #     dockerfile: Dockerfile
  #   env_file:
  #   - .env
  #   environment:
  #     - RABBIT_URL=${RABBIT_URL}
  #   command: "python consumer.py"
    
  #   depends_on:
  #     - db
  # db:
  #   image: postgres
  #   restart: always
  #   env_file:
  #     - database.env
  #   volumes:
  #     - .dbdata:/var/lib/postgresql/data

  
volumes:
  static: 
