version: "3.8"
services: 

  nginx:
    build: ../nginx
    volumes:
      - static:/static
    ports:
      - 80:80
    depends_on:
      - backend

  backend: 
    build: 
      context: . 
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - 8000:8000
    volumes:
      - static:/static
    entrypoint: ["sh","/entrypoint.sh"]
    depends_on:
      - db

  queue:
    build: 
      context: . 
      dockerfile: Dockerfile
    command: "python consumer.py"
    env_file:
      - .env
    environment:
      - RABBIT_URL=${RABBIT_URL}
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - db.env
    volumes:
      - .dbdata:/var/lib/postgresql/data
    # ports:
    # - 5432:5432

volumes:
  static:
  .dbdata: